"""Run python3 tools/bundle.py to regenerate bundle.lua. No dependencies."""
from pathlib import Path
import json
import re


def quote(source):
    equals = "="
    while "]" + equals + "]" in source:
        equals += "="
    return "[" + equals + "[\n" + source + "]" + equals + "]"


def build(root):
    sources = {
        path.stem: path.read_bytes().decode("utf-8")
        for path in sorted(root.glob("*.lua"), key=lambda path: path.name)
        if path.name not in {"loader.lua", "bundle.lua"}
    }
    main = sources["main"]
    # Match the existing loader's URL format instead of maintaining another list.
    base = re.search(r'local BaseUrl = "([^"]+)"', main)
    suffix = re.search(r'local Url = BaseUrl \.\. Name \.\. "([^"]+)"', main)
    if not base or not suffix:
        raise ValueError("main.lua Load URL format changed; update tools/bundle.py")

    output = ["-- Generated by tools/bundle.py. Edit the separate source files.\nlocal Sources = {\n"]
    for name, source in sources.items():
        output.append("    [" + json.dumps(name) + "] = " + quote(source) + ",\n")
    output.append("}\n\nlocal Responses = {}\nfor Name, Source in pairs(Sources) do\n")
    output.append("    Responses[" + json.dumps(base[1]) + " .. Name .. " + json.dumps(suffix[1]) + "] = Source\nend\n")
    output.append('''
-- Only main's local request is replaced. Module globals stay in their original environment.
local function Request(Options)
    local Source = Responses[Options.Url]
    return {StatusCode = Source and 200 or 404, Body = Source or ""}
end

-- Keep the prefix on the same line so main's error line numbers do not move.
local Main, CompileError = loadstring("local request = ...; " .. Sources.main, "=main")
if not Main then error(CompileError, 0) end
return Main(Request)
''')
    return "".join(output).encode("utf-8")


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    data = build(root)
    (root / "bundle.lua").write_bytes(data)
    print(f"Generated bundle.lua ({len(data):,} bytes)")
