"""Run python3 tools/bundle.py to regenerate bundle.lua. No dependencies."""
from pathlib import Path
import json
import re
import subprocess
from datetime import datetime, timezone


def quote(source):
    equals = "="
    while "]" + equals + "]" in source:
        equals += "="
    return "[" + equals + "[\n" + source + "]" + equals + "]"


def build(root):
    sources = {
        path.stem: path.read_bytes().decode("utf-8")
        for path in sorted(root.glob("*.lua"), key=lambda path: path.name)
        if path.name not in {"loader.lua", "bundle.lua"}
    }
    main = sources["main"]
    version = (root / "VERSION").read_text().strip()
    if not re.fullmatch(r"(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)", version):
        raise ValueError("VERSION must use major.minor.patch, e.g. 1.0.0")
    paths = [name + ".lua" for name in sources]
    paths += ["loader.lua", "VERSION", "tools/bundle.py", ".github/workflows/bundle.yml"]
    revision, timestamp = subprocess.check_output(
        ["git", "log", "-1", "--format=%H%n%ct", "--", *paths], cwd=root, text=True
    ).strip().splitlines()
    updated = datetime.fromtimestamp(int(timestamp), timezone.utc)
    metadata = {"Version": version, "Revision": revision, "Timestamp": int(timestamp),
                "Updated": updated.strftime("%d %b %Y %H:%M UTC")}
    # Match the existing loader's URL format instead of maintaining another list.
    base = re.search(r'local BaseUrl = "([^"]+)"', main)
    suffix = re.search(r'local Url = BaseUrl \.\. Name \.\. "([^"]+)"', main)
    if not base or not suffix:
        raise ValueError("main.lua Load URL format changed; update tools/bundle.py")

    output = ["-- Generated by tools/bundle.py. Edit the separate source files.\n"]
    output.append("local Build = {" + ", ".join(
        name + " = " + json.dumps(value) for name, value in metadata.items()) + "}\n")
    output.append("local Sources = {\n")
    for name, source in sources.items():
        output.append("    [" + json.dumps(name) + "] = " + quote(source) + ",\n")
    output.append("}\n\nlocal Responses = {}\nfor Name, Source in pairs(Sources) do\n")
    output.append("    Responses[" + json.dumps(base[1]) + " .. Name .. " + json.dumps(suffix[1]) + "] = Source\nend\n")
    output.append('''
-- Only main's local request is replaced. Module globals stay in their original environment.
local function Request(Options)
    local Source = Responses[Options.Url]
    return {StatusCode = Source and 200 or 404, Body = Source or ""}
end

-- Keep the prefix on the same line so main's error line numbers do not move.
local Main, CompileError = loadstring("local request, Build = ...; " .. Sources.main, "=main")
if not Main then error(CompileError, 0) end
return Main(Request, Build)
''')
    (root / "build.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    return "".join(output).encode("utf-8")


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    data = build(root)
    (root / "bundle.lua").write_bytes(data)
    print(f"Generated bundle.lua ({len(data):,} bytes)")
